### ISSUE TITLE
Split CORE into dedicated components

### ISSUE THREAD

**Issue by rpopov** [rpopov/directory-fortress-core#2]
The Fortress  Core component contains many features that are not co-related - yes, they have something in common, but from the perspective of integrating a Fortress client, having ANT and graph integrated in it (for example) is not needed.
Suggestion:
Split the core project into core-API, core-ANT, etc. sub-projects, producing separate .jar artifacts, while still producing the core .jar file for backward compatibility by merging them

**Comment by shawnmckinney** [comment]
Hi, it's an interesting idea.  However, we handle these types of requests using JIRA.  Major changes (such as this) should be discussed on the mailing list. 

[Fortress JIRA](https://issues.apache.org/jira/projects/FC/summary)
[Fortress Mailing list](http://mail-archives.apache.org/mod_mbox/directory-fortress/)

**Comment by shawnmckinney** [comment]
Which is why it took 3 weeks to answer this. We don't monitor github, it's merely a mirror of the apache git repo.  Sometimes used for accepting contributions, but little else.

**Comment by rpopov** [comment]
Sent to mailing list. Thank you!
